name: flutter_exploded
description: Display an exploded view of the render tree of a Flutter app.
version: 0.1.0+2
repository: https://github.com/blaugold/flutter_exploded
issue_tracker: https://github.com/blaugold/flutter_exploded/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  vm_service: ^7.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
