name: explo
description:
  Explore the render tree of a Flutter app in 3D, through an exploded
  representation.
version: 0.1.2
repository: https://github.com/blaugold/explo
homepage: https://github.com/blaugold/explo/main/packages/explo
issue_tracker: https://github.com/blaugold/explo/issues
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  collection: ^1.15.0
  explo_capture:
    path: ../explo_capture
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.2
  stream_channel: ^2.1.0
  vector_math: ^2.1.0
  vm_service: ^7.3.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
